is_abdomenct1k: True
is_headneck: False

abdomenct1k:
  data_root: /data_hdd/xyliu/abdomenct1k/abdomenct1k
  trainer:
    num_epochs: 400
    warmup: 5
    train_ratio: 0.8
    batch_size: 1
    lr: 0.0001
    min_lr: 0.0000001
    optimizer: adamw
    weight_decay: 0.005
    weight_decay_end: 0.04
    momentum_teacher: 0.996
    pred_ratio_var: 0
    num_workers: 8
    val_interval: 10
    gradient_accumulation_steps: 4
    
    image_size: 96
    resume: False

  finetune:
    checkpoint: abdomenct1k
  